<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="Protractor Demo App" timestamp="2019-01-11T13:05:12" hostname="localhost" time="7.489" errors="0" tests="3" skipped="0" failures="1">
  <testcase classname="Protractor Demo App" name="page should have a title" time="1.385">
  </testcase>
  <testcase classname="Protractor Demo App" name="should add one and two" time="2.124">
  </testcase>
  <testcase classname="Protractor Demo App" name="should count rows of result" time="3.979">
   <failure type="toEqual" message="Expected 3 to equal 0."><![CDATA[Error: Failed expectation
    at UserContext.<anonymous> (D:\protDemo\spec2.js:33:34)
    at C:\Users\Indrajit-PC\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\Indrajit-PC\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\Indrajit-PC\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\Indrajit-PC\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\Indrajit-PC\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\Indrajit-PC\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\Indrajit-PC\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\Indrajit-PC\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>